"""init migration

Revision ID: 13f84f39a22e
Revises: 
Create Date: 2023-07-25 23:15:40.025916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f84f39a22e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    with op.batch_alter_table('playlist_song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_song', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
