"""empty message

Revision ID: 793b183672b2
Revises: 13f84f39a22e
Create Date: 2023-07-27 23:12:32.304019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793b183672b2'
down_revision = '13f84f39a22e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_song', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
